### ISSUE TITLE
File field doesnt get populated when using Media behavior

### ISSUE THREAD

**Issue by morrislaptop** [mariuswilms/media#10]
If I have just the transfer behavior installed for a model it fills in the file field within the database, however when I add the media behavior to resize the images it doesnt save the file path into the database.

Im pretty sure this happens on line 157 of the media behavior.

Can I ask why this happens?

**Comment by mariuswilms** [comment]
The 'file' field filled in by the transfer behavior uses an absolute path. The media behavior makes that path relative (using the base path provided) and splits then it into the dirname and basename parts which end up in the corresponding fields. This way you don't have absolute paths in your table which is more flexible (e.g. when moving the folder with the media files).

**Comment by morrislaptop** [comment]
Ah I didnt have those fields in my database..

Can I also ask why it will only resize images for new records. It would  be cool if it resized when I was updating an image for a particular record.

**Comment by mariuswilms** [comment]
Please open another ticket for that, since it's a separate issue. I'd consider this as an enhancement.
