### ISSUE TITLE
Transfer behavior doesn't delete file

### ISSUE THREAD

**Issue by morrislaptop** [mariuswilms/media#12]
After deleting a record with a model attached to the transfer behavior, the behavior should delete the file.

**Comment by mariuswilms** [comment]
Transfer behavior does only handle the transfer of a file. You must use the media behavior to handle the deletion/coupling. I can see how this could be confusing. Keeping as an enhancement.

**Comment by morrislaptop** [comment]
Hmm ok well the media behavior doesnt delete the file from inside the transfer directory?

**Comment by mariuswilms** [comment]
It should delete it since the transferred file would be coupled with the database record.
