### ISSUE TITLE
PHP Warning

### ISSUE THREAD

**Issue by morrislaptop** [mariuswilms/media#13]
Warning: Call-time pass-by-reference has been deprecated; If you would like to pass it by reference, modify the declaration of array_unshift(). If you would like to enable call-time pass-by-reference, you can set allow_call_time_pass_reference to true in your INI file in /var/www/html/ilve/master/docroot/app/plugins/media/vendors/medium/medium.php on line 497

**Comment by mariuswilms** [comment]
Are you using PHP 5.3?

**Comment by morrislaptop** [comment]
5.2.6

**Comment by mariuswilms** [comment]
Under which circumstances do you get the warning? Pasting just the error message is not enough to reproduce the error which is in turn necessary to fix the potential bug.

**Comment by rchavik** [comment]
I'm getting the same error on the page by simply adding "Media.Medium" in my AppController's $helpers variable.

Forgot to mention that this is under PHP 5.2.9.

**Comment by mariuswilms** [comment]
Updating Medium classes to not explicitly use references. Closed by e027f5f49bd27ecd99a5382fa38d4faa76029e7a.
