### ISSUE TITLE
Making the file upload optional doesn't work

### ISSUE THREAD

**Issue by jtaylor77** [mariuswilms/media#14]
I have tried everything, but it won't save any record in the DB that doesn't have a file uploaded with it.  I have tried setting allowEmpty to true and required to false, but it never works.  It always fails in the beforeValidate function in the transfer behavior.

**Comment by mariuswilms** [comment]
What are you trying to accomplish? How did you setup your models? Are you using the Attachment model and saving to it via another model using saveAll()? Are you using Transfer and Media Behavior in one model? Media behavior fails to save by design if there is no file. This is because coupling only works if there's one.

**Comment by nicklinnell** [comment]
I am having the same issue with 1.3.x and cakephp 1.3.0

I have a model with the following:
<code>
class Post extends AppModel {
    var $name = 'Post';
    var $displayField = 'title';
    var $actsAs = array(
        'Media.Transfer' => array(
            'trustClient' => false,
            'baseDirectory' => MEDIA_TRANSFER,
            'createDirectory' => true,
            'alternativeFile' => 100,
        ),
        'Media.Generator' => array(
            'baseDirectory' => MEDIA,
            'filterDirectory' => MEDIA_FILTER,
            'createDirectory' => true,
        ),
        'Media.Polymorphic',
        'Media.Coupler',
        'Media.Meta' => array(
            'level'  => 2
        )
    );
}
</code>

and in my controllers:
<code>
function admin_add() {
        if (!empty($this->data)) {
            $this->Post->create();
            if ($this->Post->save($this->data)) {
                $this->Session->setFlash(sprintf(**('The %s has been saved', true), 'post'));
                $this->redirect(array('action' => 'index'));
            } else {
                $this->Session->setFlash(sprintf(**('The %s could not be saved. Please, try again.', true), 'post'));
            }
        }
    }

</code>

The posts table has dirname, basename, checksum fields.

If I add a file then the record saves correctly but if I omit the file the record does not save and the browser is redirected to the index as if it was.

Hopefully this is enough info?
