### ISSUE TITLE
Transfer adapters

### ISSUE THREAD

**Issue by mariuswilms** [mariuswilms/media#17]
Allow for multiple source and destination (direct transfer) adapters:
- FTP (http://github.com/davidpersson/media/issues#issue/6)
- S3 (https://github.com/tylerdigital/media)

**Comment by arnold-almeida** [comment]
Just checking but has there been any work on this yet?

**Comment by mariuswilms** [comment]
No not in this repository yet. Implementing such functionality would need more thought/work on my side. But I generally consider it worth being implemented in one way or another. 

Nathan Tyler has done real great work on integrating with S3. Check his repository out at https://github.com/tylerdigital/media.

**Comment by mariuswilms** [comment]
This seems to be a very good idea. Maybe something for a dedicated project?
