### ISSUE TITLE
Model value set incorrectly in attachments element

### ISSUE THREAD

**Issue by mattsmith** [mariuswilms/media#19]
On line 36 on the attachments.ctp element.
$model = $form->model();

The value of the model for the current form is set incorrectly if a HABTM input is set previously on the form.  For example, if you have a post model that HABTM  tags and you layout your add post form with the tag input just prior to the attachments element (assuming your post has attachments of course), the model value for the attachment is set to Tag (as that is the currently-used model to render the view) and not Post as it should be.

**Comment by mariuswilms** [comment]
Use the `model` setting to explicitly specify the model to use within the element:

<pre>
<?php echo $this->element('attachments', array('plugin' => 'media', 'model' => 'Post')); ?>> 
</pre>
