### ISSUE TITLE
Task make fails (wrong path)

### ISSUE THREAD

**Issue by kouak** [mariuswilms/media#20]
This is what I get when I try to cake media make :
    Error: /home/bla/webroot/media/filter/xxs/media/ could not be created or is not writable.

This path is obviously wrong.

To fix:

Replace line 137 
    $subdir = array_pop(explode(DS, dirname($this->source)));
by
    $subdir = implode(DS, array_slice(explode(DS, dirname($file)), -2, 2));

There is also a typo line 153 :
    $Folder = new Folder($directory, $this->createDirectories);
Should be 
    $Folder = new Folder($directory, $this->_createDirectories);

**Comment by adriengibrat** [comment]
Bug verified, and patch seems good, I will add it in my fork and ask for a pull!

**Comment by mariuswilms** [comment]
Fixing make task subpath parsing. Closed by 79c8e55c92c03fb1493e9992d8dbd86221c49ce9.
