### ISSUE TITLE
PDF convert fail if PDF contains more than one page

### ISSUE THREAD

**Issue by adriengibrat** [mariuswilms/media#22]
Imagick_shell convert will create multiple images with -0, -1,...-n suffix and then temporary images can not be processed!

**Comment by adriengibrat** [comment]
first trick:

```
function convert($Medium, $mimeType) {
    if (!isset($this->_formatMap[$mimeType])) {
        return false;
    }

    $Medium->mimeType = $mimeType;

    if ($Medium->name === 'Document') { // application/pdf -> image
        if ( ! is_file( $Medium->files['temporary'] ) ) {
            $Medium->files['temporary'] .= '-0';
        }
        $this->store($Medium, $Medium->files['temporary']);

        /* Unset files to prevent too early deletion by $Medium */
        $temporary = $Medium->files['temporary'];
        unset($Medium->files);

        return Medium::factory(array('temporary' => $temporary), $mimeType);
    }
    return true;
}
```

**Comment by adriengibrat** [comment]
I've tried to modify convert command line to extract only firste page, but this option uses brackets, which are escaped by _execute method... so I only have this trick to the job ;)
I'll push my code in a near future and will request a pull.

**Comment by mariuswilms** [comment]
Thanks Adrien!

**Comment by mariuswilms** [comment]
Since the ImagickShell is not available in the mm lib anymore and the Imagick PHP pecl extensions doesn't exhibit this behavior I'm closing this ticket for now. However it may become relevant again should the ImagickShell adapter be implemented in the mm lib.
