### ISSUE TITLE
basename

### ISSUE THREAD

**Issue by agborkowski** [mariuswilms/media#24]
i'm try uploaded this array
[code]
//proj1\controllers\multimedies_controller.php (line 32)
Array
(
    [Multimedy] => Array
        (
            [title] => asdasdas
            [category_id] => 1
        )

```
[Attachment] => Array
    (
        [0] => Array
            (
                [model] => Multimedy
                [group] => attachment
                [alternative] => asdsd
                [file] => Array
                    (
                        [name] => P1903080000.jpg
                        [type] => image/jpeg
                        [tmp_name] => C:\tmp\php3A13.tmp
                        [error] => 0
                        [size] => 431104
                    )

            )

    )
```

)
[/code]
[code]
$this->Multimedy->create();
            if ($this->Multimedy->saveAll($this->data,array('validate'=>'first'))) {
                debug($this->Multimedy->transfer());
                debug($this->Multimedy->transfered());
                debug($this->data);
                exit;
[/code]
and i have that errors
[code]
21  START TRANSACTION       0       0
22  INSERT INTO `multimedies` (`title`, `category_id`, `modified`, `created`, `user_id`) VALUES ('asdasdas', 1, '2009-12-21 15:01:29', '2009-12-21 15:01:29', 3)        1       0
23  SELECT LAST_INSERT_ID() AS insertID     1   1   0
24  INSERT INTO `logs` (`model_id`, `description`, `action`, `change`, `title`, `model`, `ip`, `user_id`, `created`) VALUES (18, 'Multimedy \"asdasdas\" (18) added by User \"3\" (3).', 'add', 'title, category_id, created, user_id', 'asdasdas', 'Multimedy', '127.0.0.1', 3, '2009-12-21 15:01:29')     1       0
25  SELECT LAST_INSERT_ID() AS insertID     1   1   0
26  INSERT INTO `attachments` (`model`, `group`, `alternative`, `foreign_key`, `modified`, `created`, `user_id`) VALUES ('Multimedy', 'attachment', 'asdsd', 18, '2009-12-21 15:01:29', '2009-12-21 15:01:29', 3)   1364: Field 'basename' doesn't have a default value         0
27  ROLLBACK        0       156
28  transfer    1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'transfer' at line 1            0
29  transfered  1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'transfered' at line 1
[/code]
my model
[code]
<?php
class Multimedy extends AppModel {

...
    public $actsAs = array(
        'Media.Transfer',
        ...
    );
...
    public $hasMany = array(
        'Attachment' => array(
            'className' => 'Media.Attachment',
            'foreignKey' => 'foreign_key',
            'conditions' => array('Attachment.model' => 'Multimedy'),
            'dependent' => true,
    ));

...

}
?>
[/code]

**Comment by mariuswilms** [comment]
One of the errors is coming from calling `->transfered()`. It should be `->transferred()`. The other one is coming from the fact that you call `transfer()` after calling saveAll. You just have to call saveAll. The transfer should than be automatically handled.
