### ISSUE TITLE
Replace ffmpeg adapter with ffmpeg shell adapter

### ISSUE THREAD

**Issue by flotob** [mariuswilms/media#27]
hey,

i was wondering if "native ffmpeg support" (as suggest in the media plugin presentation @cakefest berlin) means direct interaction with ffmpeg or via the php extension ffmpeg-php. Obviously, the latter is the case.
People might run into troubles when installing ffmpeg and ffmpeg-php on their system since the compliation of ffmpeg with libswscale causes screenshot extraction via ffmpeg-php to fail (as written in the respective google group). moreover, newer releases of ffmpeg do not include the option to compile ffmpeg without this library anymore (as i had to experience). might be possible to still compile without, i just don't know how to. and i don't know that disfunction that causes in ffmpeg itself.

considering all this i suggest the implementation of a ffmpeg adapter that interacts with ffmpeg directly via command line. however i cannot judge if and how this would affect security issues. i hope some linux pros can comment on that.

besides, ffmpeg-php extension can be an annoying bitch considering compilation etc. but that might just be due to my own incompetence (however, google tells me i am not alone).

i opened a discussion thread in google group here: http://groups.google.com/group/cake-php/browse_thread/thread/f6a66f984d57f3dd

**Comment by mariuswilms** [comment]
With 1.3 the "mm library":http://github.com/davidpersson/mm has been introduced. This library won't have support for the native ffmpeg extension but come with "ffmpeg shell adapter":http://github.com/davidpersson/mm/blob/master/src/Media/Process/Adapter/FfmpegShell.php
