### ISSUE TITLE
permissions bug 1.3 branch

### ISSUE THREAD

**Issue by kofi** [mariuswilms/media#29]
[enhancement/bug/1.3x]

in transfer.php  line 197
change this:  
`'permisssion' => null,`  
to :
`'permission' => null,` 

NB: incorrect spelling of permission 

also, in the Wiki for Configuration  do not define 'MEDIA' before import of the plugin core.php (I tested this only for the 1.3 branch). If this is done instead of MEDIA defaults to for example:
    `'/var/www/example.org/htdocs/media/'`
instead of 
    `'/var/www/example.org/htdocs/app/webroot/media/'`

cheers.

**Comment by mariuswilms** [comment]
Fixing typo in transfer behavior. Closed by 2f13e774d9e20dc03a7f3608a55f56a715965c14.
