### ISSUE TITLE
PDF upload using the plugin out of the box

### ISSUE THREAD

**Issue by constantine-nikolaou** [mariuswilms/media#30]
Been trying to use Media plugin attachment function in a project. I followed the steps in the tutorial and i keep getting a resizing error every time i try uploading something.

Warning (512): Medium::make - Instruction DocumentMedium::convert() failed. [APP/plugins/media/vendors/medium/medium.php, line 302]
Warning (512): MediaBehavior::make - Failed to make version xxs of file /Applications/MAMP/htdocs/cakephp/media/transfer/doc/doorbell.pdf. [APP/plugins/media/models/behaviors/media.php, line 332]
Warning (512): MediaBehavior::make - Failed to make version s of file /Applications/MAMP/htdocs/cakephp/media/transfer/doc/doorbell.pdf. [APP/plugins/media/models/behaviors/media.php, line 332]
Warning (512): MediaBehavior::make - Failed to make version m of file /Applications/MAMP/htdocs/cakephp/media/transfer/doc/doorbell.pdf. [APP/plugins/media/models/behaviors/media.php, line 332]

Is it possible to help me excluding resizing of documents? Knowing that the user might be uploading any type of files.

Many thanks
Costa

**Comment by mariuswilms** [comment]
PDF conversion only works in conjunction with ghostscript and imagemagick. If you'd like to exclude certain types from being uploaded have a look on the validations setup in the Attachment model which are supported through the transfer behavior.
