### ISSUE TITLE
MediaHelper::url() unnecessary ?

### ISSUE THREAD

**Issue by gBokiau** [mariuswilms/media#31]
I don't think it's a good idea for the Media helper to route urls of static files. AppHelper::url() isn't supposed to treat static files, hence why the function isn't called by Html::css(), script(), and the like.

In my case it causes issues because my AppHelper::url() adds language codes at the beginning of urls.

I suggest replacing all calls to MediaHelper::url() direclty to MediaHelper::webroot().

**Comment by mariuswilms** [comment]
Do not route URLs. Closed by 04e9b6cdbf9e7d815225801cd4351d49b61a3dc4.

**Comment by gBokiau** [comment]
Thanks.
Sweet bunch of commits btw, your commitment to this plugin is very much appreciated :)
