### ISSUE TITLE
Warning thrown in __db method of MimeType class

### ISSUE THREAD

**Issue by rvega** [mariuswilms/media#34]
Im using 1.3 branch and php 5.2

Warning (2): array_merge() [function.array-merge]: Argument #1 is not an array [APP/plugins/media/vendors/mime_type.php, line 299]

I removed the warning by typecasting the first param of array_merge on line 297:

```
function __db($type) {
    $searchPaths = array(
        'mime_' . $type . '.php' => array(CONFIGS),
        'mime_' . $type . '.db' => array_merge(
            (array)Configure::read('vendorPaths'),
            array(dirname(__FILE__) . DS)
        ));

    foreach ($searchPaths as $basename => $paths) {
        foreach ($paths as $path) {
            if (is_readable($path . $basename)) {
                return $path . $basename;
            }
        }
    }
}
```

**Comment by mariuswilms** [comment]
The code you post is not part of the 1.3 HEAD. It seems you're on the wrong branch. Please doublecheck you're on 1.3. 

<pre>
git clone .... media
cd media
git checkout origin/1.3
</pre>
