### ISSUE TITLE
2 issues around hasMany with grouping

### ISSUE THREAD

**Issue by ramiroaraujo** [mariuswilms/media#4]
The first one is that if I use the example as it is, I got SQL errors, because the 'group' is a reserved word. This can be solved changing 'group' to 'groping' or something like that, or writing the conditions with Model.field.

If I change the field name to grouping, I get ambiguous SQL errors if I have more than one association with different aliases. This is solved with Model.field conditions.

But, If I set Model.field conditions in the associations, when I delete the Record, the associated records (in attachments) are not deleted, because the name ( and alias ) of the model is Attachment, and not the actual Alias I set. I'm not sure how to solve this right now. Maybe manually deleting the associated data and removing 'dependent' => true, or maybe parsing some info on the beforeFind and beforeDelete of the Attachments model... :)

**Comment by mariuswilms** [comment]
Updating attachment model test case. Closed by 5499b6b64188d381d5d4d38fe7c0eed01f270051.

**Comment by mariuswilms** [comment]
I've also updated the corresponding wiki pages and snippets. I don't get any SQL errors running the attachment model test case now. If you get some then tell me which database and engine you are using.
