### ISSUE TITLE
inaccurate docblock inside media helper

### ISSUE THREAD

**Issue by kminek** [mariuswilms/media#40]
docbloc inside Media helper is refering to 'Media.Medium' instead of 'Media.Media', also consider bringing back WIKI pages here on GitHub - i am feeling little lost without those information.

**Comment by mariuswilms** [comment]
Fixing incorrect naming in docblock. Closed by 30d59836e5ddb1b9f391760865adbe9256b27405

**Comment by mariuswilms** [comment]
As a side note some reasons why the documentation has been moved from the wiki: 
- 80% of the information which has been available in the wiki has been API documentation. 
- It has been too much work to synchronize the documentation with the existing API.
- I've never really enjoyed working with Github's wiki implementation.
- The wiki didn't add any value as very very very few people would use it as such and actually edit pages.
- The docs/ directory now contains a TUTORIAL + the README has been expanded to get you started with the plugin and give you hints where to look for information. 
- Having multiple versions of the documentation was "not possible" (i.e. docs for 0.6 and 1.3)
