### ISSUE TITLE
attachment element: no preview available

### ISSUE THREAD

**Issue by bazz-** [mariuswilms/media#41]
No preview pictures are shown when using the standard element.

Changed it to look like this, now it works. But is this the cleanest way or have I not configured something correctly?

<pre>
....
/*                      if ($file = $this->Media->file($item)) { 
was like above, but condition never met, so changed to line below:
*/
                         if ($file = $media->file($item['dirname'].'/'.$item['basename']) ) {
                                $url = $this->Media->url($file);

/*                              echo $this->Media->embed($this->Media->file($previewVersion . '/', $item), array(
                                      'restrict' => array('image')
                              ));
replaced 3 lines above with line below:
 */ 
                              echo $this->Media->embed($this->Media->file($previewVersion.'/'.$item['dirname'].'/'.$item['basename']) );

                                $Media = Media::factory($file);
                                $size = $this->Media->size($file);

                                if (isset($this->Number)) {
                                        $size = $this->Number->toReadableSize($size);
                                } else {
                                        $size .= ' Bytes';
                                }
                                printf('<span class="description">%s&nbsp;(%s/%s) <em>%s</em></span>',
...
</pre>

**Comment by mariuswilms** [comment]
Updating usage of file method in element. Closed by 6d11d7e078e16bfd42a4a5f0c5733a3ea467e3de
