### ISSUE TITLE
Renaming / filtering / versioning... according to Model

### ISSUE THREAD

**Issue by djenvert** [mariuswilms/media#43]
Hello,

I'm trying to use the Media plugin with various setups. I have an "articles" and a "news" models to which I want to attach pictures through the attachment model. I'd like two things :
- first, I want to store the file under the /news/ directory or /articles/ and name it with the slug of the article/news (title-of-the-news.jpg for instance) --> seems to be a must-have for me for SEO reason, for instance
- second, I'd like to generate various versions (size) according to the model to which my picture is linked.

I'd like to have your opinion on how to implement that in the way you imagine your plugin (and also know if such code would interest you when it's done).

Thanks for your work !

**Comment by mariuswilms** [comment]
Your issue doesn't really fit into the 'bug' or 'enhancement' category.

For general support please contact the official cakephp mailing list at http://groups.google.com/group/cake-php.

As a quick hint: Have a look into the transferTo method of the TransferBehavior.

When you're filing tickets try to keep it one issue per ticket. I know that's sometimes hard. But it makes it a lot easier for me to answer and focus on the problem.
