### ISSUE TITLE
Documentation typos / minor fixes

### ISSUE THREAD

**Issue by ryandesign** [mariuswilms/media#44]
Here are some fixes for typos and other minor issues in the documentation files. The most common error seems to be confusion between "it's" and "its".

**Comment by ryandesign** [comment]
Uh, I cannot locate a file attachment facility in this issue tracker so here's a link to the patch on my server:

http://ryandesign.com/tmp/davidpersson-media.diff

**Comment by mariuswilms** [comment]
Thanks a lot for correcting the (tons of) typos. Really have to pay more attention. I'm always thankful for getting suggestions from native speakers. Closed by a74d762b1064ce3d4d82.

**Comment by ryandesign** [comment]
Glad to help. A reference I enjoy for "it's" vs "its" and other apostrophe issues is:

http://theoatmeal.com/comics/apostrophe
