### ISSUE TITLE
Fatal error: Imagick class doesn't exists on 1.3.x when imagick is not installed.

### ISSUE THREAD

**Issue by takumi-shamballah** [mariuswilms/media#46]
Hello.

I found an issue on 1.3.x when imagick is not installed.
The error is php fatal error "Fatal error: Imagick class doesn't exists"

I think it caused by Media_Info attempt to load Imagick class even if imagick is not installed.
Because default setting Media_Info::config on config/core.php in your plugin require Imagick.

So I fixed config/core.php on line 217 in your plugin followings:
- 'image' => array('ImageBasic', 'Imagick'),
- 'image' => $hasImagick ? array('ImageBasic', 'Imagick') : array('ImageBasic'),

It worked!

Thanks for your great work :)

**Comment by mariuswilms** [comment]
Applying fix suggested by &#39;takumi-shamballah&#39;. Fixes fatal error when imagick isn&#39;t in use. Closed by b8c575abaf1534b8367f34f698edce7f438da1bb.
