### ISSUE TITLE
mm library Media_Process Gd Adapter can't store jpg, and png on 1.3.x

### ISSUE THREAD

**Issue by takumi-shamballah** [mariuswilms/media#47]
Hello!

I found an issue on mm library Media_Process Gd Adapter "store" method on 1.3.x.

This method use "imagejpeg" or "imagepng" functions,
But it failed because the parameters is invalid.

If compression settings is not specified,
these functions are called with parameters: array(gdresorce, null)

But "imagejpeg" or "imagepng" functions require
 second parameters not to be NULL if the quality and filters arguments are not used. 
Then failed.

So, I suggest to unset second parameters
if compression settings is not specified.

media/libs/mm/src/Media/Process/Adapter/Gd.php on line 88
- if(count($args) === 2) unset($args[1]);

I used it, and it worked!

See the following php manual for more detail.
http://jp2.php.net/manual/en/function.imagepng.php

Thanks for your work :)

**Comment by mariuswilms** [comment]
Thanks for the report. This bug has been fixed in the mm lib repo at https://github.com/davidpersson/mm/commit/ee3ab3acb575cbbcc0aac5209981f534930b1584
