### ISSUE TITLE
Plugin doesn't delete version files

### ISSUE THREAD

**Issue by huoxito** [mariuswilms/media#48]
When deleting a register the plugin only delete files on transfer directory, So while transfer dir get always clean and organized versions directoris (l,m,s) still keep all files which doest have no relation to the database anymore.

Please let me know if I'm missing some config setting to achieve this feature.

**Comment by mariuswilms** [comment]
This feature has been removed in the 1.3 version of the plugin as versions may be organized differently and deleting those cannot properly generalized. Please implement your own deletion mechanism in the afterDelete callback of the model the respective behavior is attached to.
