### ISSUE TITLE
Database doesn't get information if no image is uploaded

### ISSUE THREAD

**Issue by bigzee** [mariuswilms/media#49]
Hi All,

Hopefully I can get some assistance with the issue I'm having here.

I have the plugin installed and everything works fine until I choose to not upload an image.  At this point none of the information from the post gets stored, even though it validates like everything went as it should.

I have looked a bit deeper and it seems that through the validation an image isn't required and the file upload box can be empty.

I'm kind of stumped.

**Comment by kiang** [comment]
Remove this line to have a quick fix:
https://github.com/davidpersson/media/blob/1.3/models/behaviors/coupler.php#L217

**Comment by mariuswilms** [comment]
This ticket has been closed in favor of #50 which describes the same problem.
