### ISSUE TITLE
cake shell can't find plugin

### ISSUE THREAD

**Issue by flamingolof** [mariuswilms/media#5]
I have downloaded the plugin and put it in the plugins folder (subfolder renamed to media) and added the require statement to my config/core.php, but when I run cake media init, cake can't find the plugin. First time I have used a plugin, so I don't know if this an issue with the plugin or cakephp

**Comment by mariuswilms** [comment]
I **cannot** confirm this with a fresh install. Did you put the plugin into @app/plugins/media@? E.g. the @media_app_controller.php@ should then be at @app/plugins/media/media_app_controller.php@. How do you invoke the shell? From your app's directory? What do you type to invoke the shell? Which operating system are you on? And what does _cake can't find the plugin_ mean?

**Comment by mariuswilms** [comment]
This seems to be a problem with your installation and not with the plugin itself. I'm closing this for now. You should try a standard install (app and cake folders side by side) and see if the problem persists. If experience the issue also with other plugins, then this could be an upstream bug. Anyway thank you for the detailed descriptions.
