### ISSUE TITLE
CouplerBehavior shouldn't unset original results when there's no file

### ISSUE THREAD

**Issue by kiang** [mariuswilms/media#50]
https://github.com/davidpersson/media/blob/1.3/models/behaviors/coupler.php#L217

I would suggest to remove this line or have an option to control it. It's an issue when using with other models which the attachment is optional.

...This is duplicated with #issue/49

**Comment by djenvert** [comment]
Oh yes, this gave me headache, and I can't understand why it's behaving like that so I hesitated a lot before removing this line. This creates very big bugs on a website I recently launched...

**Comment by letimati** [comment]
I had the same problem but i removed the unset from this line

https://github.com/davidpersson/media/blob/1.3/models/behaviors/coupler.php#L104

Then after you do this you have to change the return to true on this line as you will not be able to delete records you have saved that done have images.

https://github.com/davidpersson/media/blob/1.3/models/behaviors/coupler.php#L176

Hope this helps, great plugin.

**Comment by mariuswilms** [comment]
Removing skipping of nonexistent files in CouplerBehavior.

This proved to be unexpected behavior.

Allowing records to not have a corresponding file. If you&#39;d still want
to enforce each record having a valid corresponding file you must now
use the sync shell task to detect potential invalid records.

Closed by 2a188ed85f69a9cf361964b84015c4b21d1137fc. Refs #49.
