### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by darkcloud-xx** [mariuswilms/media#51]
Some libraries that use uppercase letters in filenames may not be included. For example, the file core.php.

require_once (/ Mime / Type.php) causes a "Fatal error: require_once () [function.require]: Failed opening required '/ Mime / Type.php'"

It is a rare bug, but still sometimes occur. I had this bug on 1and1.com hosting

**Comment by mariuswilms** [comment]
This seems to be a problem with your hosting environment (as you describe). Under normal circumstances there shouldn't be a problem with casing in filenames. Are you sure this has something to do with the casing?

**Comment by darkcloud-xx** [comment]
Yes, it's a hosting problem caused by uppercase letters. I simply renamed libraries and now works fine.
