### ISSUE TITLE
Pdf upload: Uncaught exception 'BadMethodCallException' with message 'No source given.'

### ISSUE THREAD

**Issue by 3wv** [mariuswilms/media#52]
I have Imagick and Ghostscript on and running, I have checked it with simple php scripts.

The pdf gets uploaded into the transfer folder.

But I get a Fatal Error:

<br />
<b>Fatal error</b>:  Uncaught exception 'BadMethodCallException' with message 'No source given.' in /usr/home/xy/domains/cake_1.3/cake_dc/plugins/media/libs/mm/src/Media/Process.php:49
Stack trace:
#0 /usr/home/xy/domains/cake_1.3/cake_dc/plugins/media/libs/mm/src/Media/Process/Generic.php(114): Media_Process::factory(Array)
#1 [internal function]: Media_Process_Generic-&gt;convert('image/png')
#2 /usr/home/xy/domains/cake_1.3/cake_dc/plugins/media/models/behaviors/generator.php(208): call_user_func_array(Array, Array)
#3 /usr/home/xy/domains/cake_1.3/cake/libs/model/model_behavior.php(171): GeneratorBehavior-&gt;makeVersion(Object(Someobj), '/usr/home/xy...', Array)
#4 /usr/home/xy/domains/cake_1.3/cake/libs/model/model_behavior.php(467): ModelBehavior-&gt;dispatchMethod(Object(Someobj), 'makeVersion', Array)
#5 /usr/home/xy/domains/cake_1.3/cake/libs/model/model.php(496): BehaviorCollection-&gt;dispatchMethod(Object(Someobj), 'makeVersion', Array)
#6 /usr/home/xy/domains/cake_1.3/cake/libs/ov in <b>/usr/home/xy/domains/cake_1.3/cake_dc/plugins/media/libs/mm/src/Media/Process.php</b> on line <b>49</b><br />

What I am doing wrong?

**Comment by 3wv** [comment]
Ok, I have figured out, how it would work, but it is not a proper way for sure:

I have changed /mm/src/Mime/Type.php

```
    //'application/pdf'       => 'document',
    'application/pdf'       => 'image',
```

in order to have a pdf treated like an image. The s, m and l versions are created as expected.
This probably means that the plain plugin installation will always cause an error by uploading a pdf (or another doc).

**Comment by 3wv** [comment]
The problem seems to be in media/libs/mm/src/Media/Process/Generic.php

on line 110:
if ($this->name() != Mime_Type::guessName($mimeType)) { // i.e. document -> image

By creating a thumb out of a pdf this will result in a 'document' != 'image' (as hinted in your comment)

on line 114:
$media = Media_Process::factory(array('adapter' => $this->_adapter));

There is no source given, but "Media_Process::factory()" asks for an adapter and a source as in media/libs/mm/src/Media/Process.php

starting on line 44ff:
public static function &factory(array $config = array()) {
    $default = array('source' => null, 'adapter' => null);
    extract($config + $default);

```
if (!$source) {
    throw new BadMethodCallException("No source given.");
}
```

As there is no source passed, none can be found and the error is triggered.

Adding the absolute path as a source and passing it, makes it work.

**Comment by mariuswilms** [comment]
Hi 3wv,  
First of all thanks for your report and analysis. It seems you're running an older version of the plugin (and the libraries it contains). It's possible that this doesn't help anything but just to be sure this wasn't already solved in a later version you're running: Please update to the latest version of the plugin. 

Also make sure you're using the Imagick adapter for both document and image conversions.

<pre>
Media_Process::config(array(
    'document' => 'Imagick',
    'image' => 'Imagick'
));
</pre>

**Comment by mariuswilms** [comment]
I'm closing this ticket for now as it seems to be fixed. Feel free to reopen if it ain't so.
