### ISSUE TITLE
Files from filter directory are not deleted

### ISSUE THREAD

**Issue by darkcloud-xx** [mariuswilms/media#53]
I'm using included Attachment model. When I'm adding img file "cover.jpg" everything is ok:

webroot\media\transfer\img\cover.jpg - Added
webroot\media\filter\l\img\cover.jpg - Added
webroot\media\filter\m\img\cover.jpg - Added
webroot\media\filter\s\img\cover.jpg - Added

but when I'm trying to delete record from database:

webroot\media\transfer\img\cover.jpg - Deleted
webroot\media\filter\l\img\cover.jpg - Not Deleted
webroot\media\filter\m\img\cover.jpg - Not Deleted
webroot\media\filter\s\img\cover.jpg - Not Deleted

It's not big deal but if I have new file with name "cover.jpg" and I trying add it then files from filter directory are not replaced.

**Comment by mariuswilms** [comment]
This is the intended behavior. Please see issue #48 and https://gist.github.com/859371 for an example implementation to get back the functionality.
