### ISSUE TITLE
imagick crashing

### ISSUE THREAD

**Issue by pkirk** [mariuswilms/media#55]
Hi,
and thanks for your work.

I got this error on shared hosting services.

<pre>

[Fri Apr 01 13:38:37 2011] [error] [client xx.xx.xx.xx] php: magick/resize.c:581: AcquireResizeFilter: Assertion `UndefinedFilter < filter && filte
r < SentinelFilter' failed., referer: http://www.example.com/products/edit/1
[Fri Apr 01 13:38:37 2011] [error] [client xx.xx.xx.xx] Premature end of script headers: index.php, referer: http://www.example.com/products/edit/1

</pre>

Using gd (putting $hasImagick = false;) removes the problem.

Is there any chance to have a config value to choose between Imagemagik and gd?

Thanks

**Comment by mariuswilms** [comment]
This seems to be a problem with the way imagemagick is compiled on your site. As an alternative to editing the plugins core.php you might want to override the settings which use imagick by adding a repeating block of `Media_Process::config(...)` within your app's core.php right after including the plugin configuration.
