### ISSUE TITLE
Not saving associated model's record on create

### ISSUE THREAD

**Issue by bradmaxs** [mariuswilms/media#59]
More than one of my apps are doing this so I am very confused.  I am using Show hasMany Attachment.  I try and create a new record and it uploads and resizes the image and saves the record to my Attachment model without a foreign_key but with the correct model (Show).

However, it does NOT save the main record in my Show model.  The flash says the record has been saved but it hasn't.  If I EDIT a preexisting record, the image is uploaded, resized and saved to the Attachment db with the foreign_key.

Any help would be greatly appreciated.  I would really like to be able to use this plugin as it looks amazing but can't figure this one hurdle out.

Thank you.

**Comment by mariuswilms** [comment]
Please repost this request on the official cakephp mailinglist. It's a better place to answer support request and general questions. http://groups.google.com/group/cake-php/topics

**Comment by bradmaxs** [comment]
Thanks David,

I posted there.
