### ISSUE TITLE
creating new record with saveAll

### ISSUE THREAD

**Issue by michalmalinowski** [mariuswilms/media#62]
Hey,

I have the same problem as bradmaxs:

http://groups.google.com/group/cake-php/browse_thread/thread/aa331e6a9938f242?fwc=1&pli=1#

When created new record in database system is not saving data, but when I will edit record everything is fine. What could be the cause? One thing that I can mention about my system is that I'm not using auto-increment in db, I'm creating uniqid() in controller before saveAll(). Any suggestion why its not working? Please advise.

Michal

**Comment by mariuswilms** [comment]
@michalmalinowski can you provide a failing test case for this? A good place to look for similar ones and add one is https://github.com/davidpersson/media/blob/next/tests/cases/models/attachment.test.php in case you're able to identify a behavior is causing the problems have a look at the tests in https://github.com/davidpersson/media/tree/next/tests/cases/models/behaviors.

**Comment by mariuswilms** [comment]
Closing - this maybe has already been resolved. Feel free to reopen with more information.
