### ISSUE TITLE
Plugin not working in XAMPP under windows, no error reported

### ISSUE THREAD

**Issue by wangshijun** [mariuswilms/media#63]
I have installed the plugin with XAMPP under windows, and have checked that all file locations and setups are correct, just as the plugin documentation said, but the plugin is not working

**Comment by davearroyo** [comment]
I get this error.

Fatal error: Call to undefined method MIME_Type::config() in C:\xampp\htdocs\sofish\plugins\media\config\core.php on line 165

**Comment by Kanickl** [comment]
I get almost the same error message:
"PHP Fatal error:  Call to undefined method MIME_Type::config() in C:\Projekte\sc
hlaglochfinder\htdocs\sfinder\plugins\media\config\core.php on line 166

Fatal error: Call to undefined method MIME_Type::config() in C:\Projekte\schlagl
ochfinder\htdocs\sfinder\plugins\media\config\core.php on line 166"

I am using XAMPP 1.7.4 (Apache 2.2.17 MySQL 5.5.8 PHP 5.3.5) on Windows 7

would be great if there was a fix for that.

**Comment by jeremyharris** [comment]
The problem is that there is a PEAR class called MIME_Type as well. Since it's in the $PATH, it uses that class first instead of Media's. A bit of a namespace issue.

**Comment by mariuswilms** [comment]
Oh noes -- thanks for hunting that down. I can see that reordering the include path may be an option to fix this.

**Comment by ReplicaObscura** [comment]
I can confirm that using this instead seems to reference the proper class:

`ini_set('include_path', $mm.DS.'src'.PATH_SEPARATOR.ini_get('include_path'));`
