### ISSUE TITLE
Documentation links to wiki that doesn't exist

### ISSUE THREAD

**Issue by richardathome** [mariuswilms/media#64]
As a first time user of the Media plugin I was a little frustrated trying to find any documentation :-(

The README that comes with the plugin points to wiki pages on github that no longer exist.

After quite a lot of googling I found a page that mentioned the wiki had been moved into a docs/directory:

https://github.com/davidpersson/media/tree/next/docs

The link in the post was wrong but it gave me enough clues to dig around and find it.

Please update the the README file to point new users at the documentation.

**Comment by mariuswilms** [comment]
The master branch will soon get replaced with next. There currently is no documentation for 0.6 which indeed isn't perfect. On the other hand backporting/retrofitting the docs from next now isn't probably worth the effort. For now users will need to use the docs available under the link you've posted.
