### ISSUE TITLE
MediaShell could not be loaded

### ISSUE THREAD

**Issue by 8vius** [mariuswilms/media#65]
I'm following the tutorial bundled with the project, I have cloned the plugin into my app/plugins folder under a subfolder named media as you instruct. 

I've placed require APP.'plugins/media/config/core.php';  in my core.php then I try to run cake/console/cake media init, when I do I get the error in the title, I have no idea what's wrong, I'm running on Mac OS X Snow Leopard and I'm using XAMPP.

**Comment by hiromi2424** [comment]
try replacing require with require_once. otherwise I have no idea

**Comment by 8vius** [comment]
Nope, that didn't work, guess I'll just have to manually make the folders, does the shell perform any other operation besides this?

**Comment by jeremyharris** [comment]
First, make sure that the media shell is available by running `$ cake` (no args). It will tell you what shells are available. If media is not available, make sure that the plugin is being properly loaded and that you are pointing to the correct app (using the `-app` param on the baking shell).

**Comment by mariuswilms** [comment]
This seems to be problem that isn't specific to the media plugin, but to loading plugin shells with your CakePHP setup.
