### ISSUE TITLE
Issue saving record without attached image

### ISSUE THREAD

**Issue by kro12** [mariuswilms/media#71]
Hi, thanks for a great plugin.
I am saving a Rate record and an associated image . Everything works fine when an image is added, when an image isn't added the Rate record gets corrupted.

The array is as follows:

Array ( [Rate] => Array ( [enabled] => 0 [is_corporate] => 0 [special_offer] => 0 [list_no] => 0 [id_ref] => 43564566 [title] => rate7 [price_quote_as] => 0 [adult_supplement] => 0 [child_supplement] => 0 [supplement] => 0 [short_description] => rate7 [description] =>

rate7 [available] => Array ( [0] => 2 ) [minimum_stay] => 0 [maximum_stay] => 0 [valid_from] => 2012-02-24 [valid_to] => 2012-02-25 [file] => Array ( [name] => [type] => [tmp_name] => [error] => 4 [size] => 0 ) ) [Room] => Array ( [Room] => Array ( [0] => 16 ) ) )

Note the 'file' array with the error 4.

When I remove the 'Media.Coupler' from the model the Rate record is written correctly but the image data is lost.
Regards,
Kro

**Comment by mariuswilms** [comment]
The coupler behavior was created with the assumption it is bound to a table which deals just with files. So that line was preventing any new record to be created if there was no file. Creating a record without a file for i.e. a "files" table doesn't make sense.

However this isn't fitting for your scenario, which is totally legitimate. To make your case work this line actually needs to be removed. I'm wondering if there's anything preventing this. I have to research a bit and see.

Related line (which was pointed out to me in another discussion):
https://github.com/davidpersson/media/blob/next/models/behaviors/coupler.php#L104

**Comment by jeremy-burns** [comment]
This is my use case too. A user record has the fields needed to store an optional image, but it is legitimate for the user not to upload one. When the image fields are empty the Media.Coupler unsets the User data and the User->save fails. My (nervous) workaround is to comment out the line in Media.Coupler that unsets the [User] data, which fixes my issue. It also doesn't appear to have harmed other instances where I am using the coupler to manage tables dedicated to images, but that is why I am nervous.

**Comment by RabidFire** [comment]
@davidpersson: First off, amazing plugin!

I have to agree with the rest of the people who've faced this issue. It's extremely hard to debug this, given that save() will return true if $this->data is unset. So, the user gets a success message, but the database is untouched!

If the file fields are required (ie. they're the primary fields that identify a record in, say, an 'attachments' or 'files' table), it would be more flexible if we could add that as a validation rule for those models. Please let me know what you think.

Right now, I'm doing something like this:

```
function beforeValidate() {
    if (!empty($this->data[$this->alias]['file']['size'])) {
        $this->Behaviors->attach('Media.Transfer');
        $this->Behaviors->attach('Media.Coupler');
        $this->Behaviors->attach('Media.Generator');
    } else {
        unset($this->data[$this->alias]['file']);
    }
}
```

This will load the behaviors on demand. I'm currently using this as a workaround for models where the file field is optional. Hope this helps someone!

**Comment by kro12** [comment]
Thanks for taking the time to reply @davidpersson. I ended up using the same workaround as @classoutfit, and it has been working without any noticeable issues.
