### ISSUE TITLE
Extension validation always failed

### ISSUE THREAD

**Issue by ghost** [mariuswilms/media#73]
Hi,

I'm using Cake 1.3.14 and your 1.3 plugin, under Win XP.

I'm using your "attachments" element to generate my upload fields (by the way, I think it is missing a hidden field for "foreign_key" in the element, otherwise the save fails...).

The issue is when I make a saveAll($data,array('validate'=>true)) or saveAll($data,array('validate'=>'first')) , I've always a validation error for "file extension", but if I make a $this->Attachement->validates() before the save, all validation rules are ok...

Here is my Attachment model with plugin configuration and validate:

```
public $actsAs = array(
    'Media.Transfer' => array(
        'trustClient' => false,
        'transferDirectory' => MEDIA_TRANSFER,
        'createDirectory' => true,
        'alternativeFile' => 100
    ),
    'Media.Polymorphic',
    'Media.Coupler' => array(
        'baseDirectory' => MEDIA_TRANSFER
    ),
    'Media.Meta' => array(
        'level' => 2
    ),
    'Ordonnable' => array(
        'field' => 'display_order',
        'addToEnd' => true,
        'conditional_fields' => array('model','foreign_key')
    )
);

public $validate = array(
    'file' => array(
        'resource'   => array('rule' => 'checkResource'),
        'access'     => array('rule' => 'checkAccess'),
        'permission' => array('rule' => array('checkPermission', '*')),
        'size'       => array('rule' => array('checkSize', '5M')),
        'pixels'     => array('rule' => array('checkPixels', '1600x1600')),
        'extension'  => array('rule' => array('checkExtension', false, array(
            'jpg', 'jpeg', 'png'
        ))),
        'mimeType'   => array('rule' => array('checkMimeType', false, array(
            'image/jpeg', 'image/png'
        )))
    ),
    'alternative' => array(
        'rule'       => 'checkRepresent',
        'on'         => 'create',
        'required'   => false,
        'allowEmpty' => true,
));
```

Here is my view form:

<pre><code>
    echo $this->Form->create('Apartment',array('url'=>array('controller'=>'attachments','action'=>'add'),'type'=>'file')); 
    echo $this->element('attachments', array('plugin'=>'Media'));
    echo $this->Form->end(__('Save',true)); 
</code>
</pre>

Here is my Attachments::add method:

<pre><code>
public function admin_add() {
        if (!empty($this->data)) {
            $this->Attachment->create();
            if ($this->Attachment->saveAll($this->data['Attachment'],array('validate'=>true,'atomic'=>false))) {
                $this->Session->setFlash(__('Attachment saved.', true),'success_message',array(),'flash_admin');
                $this->redirect('/');
            } else {
                $this->Session->setFlash(__('Attachment could not be saved. Please, try again.', true),'error_message',array(),'flash_admin');
            }
        }
}
</code>
</pre>

I am trying with real .jpg images and neither file is uploaded, neither record is saved...
If I make a debug($errors) in Model::validates(), it always returns "file" => "extension".
But if I make "validate->false" in my saveAll, it works.

**Comment by mariuswilms** [comment]
Thank you for your report. Unfortunately this issue is very old. Feel free to reopen if this is still a problem.
